### ISSUE TITLE
Peer-to-peer Code Review - Team Feedback.

### ISSUE THREAD

**Issue by udberg** [KumarAmitt/vetect#1]
- Your work looks good and almost done, but you can position the text in your search button to center properly because it is currently aligned towards the top, and giving so much space on the bottom.
- In your tablet version, you can change the search bar button to the color blue to meet original specifications, but this is optional.
- On your about page, you can put the logo beside the heading.
- Font style of your box in the mobile version can be changed but this is optional too.

Goodluck!

**Comment by KumarAmitt** [comment]
Thanks for the feedback. Considered your suggestions to improve this project.
